"""Regenerate responses with the target model itself (on-policy distillation data).

Mirrors DSpark's data recipe: Open-PerfectBlend prompts, responses regenerated by
the target model in non-thinking mode. Run inside .venv-vllm.
"""

import argparse
import json
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="Qwen/Qwen3-0.6B")
    ap.add_argument("--n", type=int, default=120_000)
    ap.add_argument("--max-tokens", type=int, default=512)
    ap.add_argument("--out", default="data/regen_qwen3_0.6b.jsonl")
    ap.add_argument("--temperature", type=float, default=1.0)
    ap.add_argument("--top-p", type=float, default=0.95)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    from datasets import load_dataset
    from transformers import AutoTokenizer
    from vllm import LLM, SamplingParams

    tok = AutoTokenizer.from_pretrained(args.model)
    ds = load_dataset("mlabonne/open-perfectblend", split="train", streaming=True)

    prompts, raw = [], []
    for ex in ds:
        msgs = ex["conversations"]
        # first human turn only -> single-turn regeneration
        first = next((m for m in msgs if m.get("from") in ("human", "user")), None)
        if first is None or not first["value"].strip():
            continue
        text = first["value"].strip()
        if len(text) > 4000:
            continue
        templ = tok.apply_chat_template(
            [{"role": "user", "content": text}],
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )
        if len(tok(templ, add_special_tokens=False)["input_ids"]) > 1400:
            continue
        raw.append(text)
        prompts.append(templ)
        if len(prompts) >= args.n:
            break
    print(f"collected {len(prompts)} prompts")

    llm = LLM(model=args.model, dtype="bfloat16", gpu_memory_utilization=0.85,
              max_model_len=2048, seed=args.seed)
    sp = SamplingParams(temperature=args.temperature, top_p=args.top_p,
                        max_tokens=args.max_tokens, seed=args.seed)
    outs = llm.generate(prompts, sp)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    n_ok = 0
    with out.open("w") as f:
        for p, o in zip(raw, outs):
            txt = o.outputs[0].text
            if not txt.strip():
                continue
            f.write(json.dumps({"prompt": p, "response": txt}) + "\n")
            n_ok += 1
    print(f"wrote {n_ok} samples to {out}")


if __name__ == "__main__":
    main()
